### ISSUE TITLE
Create Layout for Game Dialogs(List View and Click Listeners)

### ISSUE THREAD

**Issue by JamesNikolaidis** [TransCoders/The_Elucidated#11]
Create Layout for users interaction with other people or objects. For example if user finds a note , it will appear a list with available options for the user.

**Comment by TasosTilsi** [comment]
I did it in my branch...Half of it!

**Comment by Hibye-Yo** [comment]
kleine ta issue otan ta kaneis kai kanta pull ston dev. Apo ekei 8a ta testaroume kai meta 8a ta pairname ston master an doulevoun kala.
