### ISSUE TITLE
Create a smart way witch calcalate the distance that user cover if network stops for a reason

### ISSUE THREAD

**Issue by JamesNikolaidis** [TransCoders/The_Elucidated#23]
If user lose unexpected the  mobile data connectivity , but the app is still open , we must have a method which will calculate approximately  of the distance that user may cover . For example if user was so close to find an object and somehow the  internet was disconnected , the app will still running but it will not have user's location and so it will pass the object and because of the bad connection ,user  will loose one clue.

**Comment by damisv** [comment]
No one can know for sure the distance either the direction the user was going.The app doesn't need that anyway: if there is a data connection error , also the database cannot be accessed.So no need of such thing.
An error dialog should be enough.
