### ISSUE TITLE
Create Inventory view

### ISSUE THREAD

**Issue by Hibye-Yo** [TransCoders/The_Elucidated#58]
Kane ena activty i ena menu otidipote , gia na mporoume na deixnoume ston xristi ti item exei vrei mexri tora

**Comment by TasosTilsi** [comment]
Το έχω κάνει το θέμα είναι οι συναρτήσεις με την βάση για το inventory του κάθε παίκτη.
Θα κουμπώσουμε τις συναρτήσεις και θα είναι έτοιμο!
